# Generated by Django 4.2.3 on 2023-08-29 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
                ('profile_pic', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Scout', 'Scout'), ('Parent', 'Parent'), ('leader', 'Leader')], default='Scout', max_length=15)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('SPL', 'Senior Patrol Leader'), ('ASPL', 'Assistant Senior Patrol Leader'), ('PL', 'Patrol Leader'), ('Bugler', 'Bugler'), ('Troop Guide', 'Troop Guide'), ('Quartermaster', 'Quartermaster'), ('Troop Scribe', 'Troop Scribe'), ('TOAR', 'Troop Order of the Arrow Representative'), ('Troop Historian', 'Troop Historian'), ('Instructor', 'Instructor'), ('Chaplain Aide', 'Chaplain Aide'), ('Den Chief', 'Den Chief'), ('Webmaster', 'Webmaster'), ('Webelos Deb Chief', 'Webelos Deb Chief'), ('Outdoor Ethics Guide', 'Outdoor Ethics Guide'), ('JA Scoutmaster', 'Junior Assistant Scoutmaster')], max_length=35)),
                ('rank', models.CharField(choices=[('Scout', 'Scout'), ('Tenderfoot', 'Tenderfoot'), ('Second Class', 'Second Class'), ('First Class', 'First Class'), ('Star', 'Star'), ('Life', 'Life'), ('Eagle', 'Eagle')], default='Scout', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('bsa_id', models.CharField(max_length=25)),
                ('position', models.CharField(choices=[('Scoutmaster', 'Scoutmaster'), ('Assistant Scoutmaster', 'Assistant Scoutmaster'), ('Committee Chairman', 'Committee Chairman'), ('Committee Member', 'Committee Member'), ('Charter Organization Representative', 'Charter Organization Representative')], max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
