# Generated by Django 4.2.3 on 2023-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=125)),
                ('details', models.TextField()),
                ('requirements', models.CharField(max_length=250)),
                ('reminder', models.DateTimeField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
