# Generated by Django 4.2.3 on 2023-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeritBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('eagle_required', models.BooleanField(default=False)),
                ('logo_image', models.CharField(max_length=100)),
            ],
        ),
    ]
